//! Named UI element colors for the workbench (editor chrome).
//!
//! Covers 180+ VS Code workbench color keys.

use serde::{Deserialize, Serialize};

use crate::color::Color;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct WorkbenchColors {
    pub editor_background: Option<Color>,
    pub editor_foreground: Option<Color>,
    pub editor_line_highlight_background: Option<Color>,
    pub editor_selection_background: Option<Color>,
    pub editor_selection_foreground: Option<Color>,
    pub editor_inactive_selection_background: Option<Color>,
    pub editor_selection_highlight_background: Option<Color>,
    pub editor_find_match_background: Option<Color>,
    pub editor_find_match_highlight_background: Option<Color>,
    pub editor_find_range_highlight_background: Option<Color>,
    pub editor_word_highlight_background: Option<Color>,
    pub editor_word_highlight_strong_background: Option<Color>,
    pub editor_line_number_foreground: Option<Color>,
    pub editor_line_number_active_foreground: Option<Color>,
    pub editor_cursor_foreground: Option<Color>,
    pub editor_cursor_background: Option<Color>,
    pub editor_whitespace_foreground: Option<Color>,
    pub editor_indent_guide_background: Option<Color>,
    pub editor_indent_guide_active_background: Option<Color>,
    pub editor_ruler_foreground: Option<Color>,
    pub editor_bracket_match_background: Option<Color>,
    pub editor_bracket_match_border: Option<Color>,
    pub editor_overview_ruler_border: Option<Color>,
    pub editor_gutter_added_background: Option<Color>,
    pub editor_gutter_modified_background: Option<Color>,
    pub editor_gutter_deleted_background: Option<Color>,
    pub editor_error_foreground: Option<Color>,
    pub editor_error_border: Option<Color>,
    pub editor_warning_foreground: Option<Color>,
    pub editor_warning_border: Option<Color>,
    pub editor_info_foreground: Option<Color>,
    pub editor_info_border: Option<Color>,
    pub editor_hint_foreground: Option<Color>,
    pub editor_hover_highlight_background: Option<Color>,
    pub editor_link_active_foreground: Option<Color>,
    pub editor_sticky_scroll_background: Option<Color>,
    pub editor_sticky_scroll_hover_background: Option<Color>,
    pub editor_sticky_scroll_border: Option<Color>,
    pub editor_widget_background: Option<Color>,
    pub editor_widget_foreground: Option<Color>,
    pub editor_widget_border: Option<Color>,
    pub editor_suggest_widget_background: Option<Color>,
    pub editor_suggest_widget_border: Option<Color>,
    pub editor_suggest_widget_foreground: Option<Color>,
    pub editor_suggest_widget_selected_background: Option<Color>,
    pub editor_suggest_widget_highlight_foreground: Option<Color>,
    pub editor_hover_widget_background: Option<Color>,
    pub editor_hover_widget_foreground: Option<Color>,
    pub editor_hover_widget_border: Option<Color>,
    pub editor_hover_widget_status_bar_background: Option<Color>,
    pub editor_inlay_hint_foreground: Option<Color>,
    pub editor_inlay_hint_background: Option<Color>,
    pub editor_light_bulb_foreground: Option<Color>,
    pub editor_light_bulb_auto_fix_foreground: Option<Color>,
    pub editor_group_border: Option<Color>,
    pub editor_group_header_tabs_background: Option<Color>,
    pub editor_group_header_tabs_border: Option<Color>,
    pub editor_group_header_no_tabs_background: Option<Color>,
    pub editor_pane_background: Option<Color>,
    pub side_bar_background: Option<Color>,
    pub side_bar_foreground: Option<Color>,
    pub side_bar_border: Option<Color>,
    pub side_bar_title_foreground: Option<Color>,
    pub side_bar_section_header_background: Option<Color>,
    pub side_bar_section_header_foreground: Option<Color>,
    pub side_bar_section_header_border: Option<Color>,
    pub activity_bar_background: Option<Color>,
    pub activity_bar_foreground: Option<Color>,
    pub activity_bar_inactive_foreground: Option<Color>,
    pub activity_bar_border: Option<Color>,
    pub activity_bar_active_border: Option<Color>,
    pub activity_bar_active_background: Option<Color>,
    pub activity_bar_badge_background: Option<Color>,
    pub activity_bar_badge_foreground: Option<Color>,
    pub status_bar_background: Option<Color>,
    pub status_bar_foreground: Option<Color>,
    pub status_bar_border: Option<Color>,
    pub status_bar_debugging_background: Option<Color>,
    pub status_bar_debugging_foreground: Option<Color>,
    pub status_bar_debugging_border: Option<Color>,
    pub status_bar_no_folder_background: Option<Color>,
    pub status_bar_no_folder_foreground: Option<Color>,
    pub status_bar_no_folder_border: Option<Color>,
    pub status_bar_item_hover_background: Option<Color>,
    pub status_bar_item_active_background: Option<Color>,
    pub status_bar_item_prominent_background: Option<Color>,
    pub status_bar_item_prominent_hover_background: Option<Color>,
    pub status_bar_item_remote_background: Option<Color>,
    pub status_bar_item_remote_foreground: Option<Color>,
    pub status_bar_item_error_background: Option<Color>,
    pub status_bar_item_error_foreground: Option<Color>,
    pub status_bar_item_warning_background: Option<Color>,
    pub status_bar_item_warning_foreground: Option<Color>,
    pub tab_active_background: Option<Color>,
    pub tab_active_foreground: Option<Color>,
    pub tab_inactive_background: Option<Color>,
    pub tab_inactive_foreground: Option<Color>,
    pub tab_border: Option<Color>,
    pub tab_active_border: Option<Color>,
    pub tab_active_border_top: Option<Color>,
    pub tab_unfocused_active_background: Option<Color>,
    pub tab_unfocused_active_foreground: Option<Color>,
    pub tab_unfocused_inactive_background: Option<Color>,
    pub tab_unfocused_inactive_foreground: Option<Color>,
    pub tab_hover_background: Option<Color>,
    pub tab_hover_foreground: Option<Color>,
    pub tab_hover_border: Option<Color>,
    pub tab_last_pinned_border: Option<Color>,
    pub panel_background: Option<Color>,
    pub panel_foreground: Option<Color>,
    pub panel_border: Option<Color>,
    pub panel_title_active_foreground: Option<Color>,
    pub panel_title_active_border: Option<Color>,
    pub panel_title_inactive_foreground: Option<Color>,
    pub panel_input_border: Option<Color>,
    pub panel_section_border: Option<Color>,
    pub panel_section_header_background: Option<Color>,
    pub panel_section_header_foreground: Option<Color>,
    pub list_hover_background: Option<Color>,
    pub list_hover_foreground: Option<Color>,
    pub list_active_selection_background: Option<Color>,
    pub list_active_selection_foreground: Option<Color>,
    pub list_active_selection_icon_foreground: Option<Color>,
    pub list_inactive_selection_background: Option<Color>,
    pub list_inactive_selection_foreground: Option<Color>,
    pub list_focus_background: Option<Color>,
    pub list_focus_foreground: Option<Color>,
    pub list_focus_outline: Option<Color>,
    pub list_highlight_foreground: Option<Color>,
    pub list_drop_background: Option<Color>,
    pub list_invalid_item_foreground: Option<Color>,
    pub list_error_foreground: Option<Color>,
    pub list_warning_foreground: Option<Color>,
    pub list_deemphasized_foreground: Option<Color>,
    pub tree_indent_guides_stroke: Option<Color>,
    pub tree_table_columns_border: Option<Color>,
    pub input_background: Option<Color>,
    pub input_foreground: Option<Color>,
    pub input_border: Option<Color>,
    pub input_placeholder_foreground: Option<Color>,
    pub input_option_active_background: Option<Color>,
    pub input_option_active_border: Option<Color>,
    pub input_option_active_foreground: Option<Color>,
    pub input_option_hover_background: Option<Color>,
    pub input_validation_info_background: Option<Color>,
    pub input_validation_info_foreground: Option<Color>,
    pub input_validation_info_border: Option<Color>,
    pub input_validation_warning_background: Option<Color>,
    pub input_validation_warning_foreground: Option<Color>,
    pub input_validation_warning_border: Option<Color>,
    pub input_validation_error_background: Option<Color>,
    pub input_validation_error_foreground: Option<Color>,
    pub input_validation_error_border: Option<Color>,
    pub dropdown_background: Option<Color>,
    pub dropdown_foreground: Option<Color>,
    pub dropdown_border: Option<Color>,
    pub dropdown_list_background: Option<Color>,
    pub button_background: Option<Color>,
    pub button_foreground: Option<Color>,
    pub button_hover_background: Option<Color>,
    pub button_border: Option<Color>,
    pub button_secondary_background: Option<Color>,
    pub button_secondary_foreground: Option<Color>,
    pub button_secondary_hover_background: Option<Color>,
    pub badge_background: Option<Color>,
    pub badge_foreground: Option<Color>,
    pub scroll_bar_shadow: Option<Color>,
    pub scrollbar_slider_background: Option<Color>,
    pub scrollbar_slider_hover_background: Option<Color>,
    pub scrollbar_slider_active_background: Option<Color>,
    pub progress_bar_background: Option<Color>,
    pub notification_background: Option<Color>,
    pub notification_foreground: Option<Color>,
    pub notification_border: Option<Color>,
    pub notification_center_header_background: Option<Color>,
    pub notification_center_header_foreground: Option<Color>,
    pub notification_link_foreground: Option<Color>,
    pub title_bar_active_background: Option<Color>,
    pub title_bar_active_foreground: Option<Color>,
    pub title_bar_inactive_background: Option<Color>,
    pub title_bar_inactive_foreground: Option<Color>,
    pub title_bar_border: Option<Color>,
    pub menu_background: Option<Color>,
    pub menu_foreground: Option<Color>,
    pub menu_border: Option<Color>,
    pub menu_selection_background: Option<Color>,
    pub menu_selection_foreground: Option<Color>,
    pub menu_selection_border: Option<Color>,
    pub menu_separator_background: Option<Color>,
    pub peek_view_border: Option<Color>,
    pub peek_view_editor_background: Option<Color>,
    pub peek_view_editor_match_highlight_background: Option<Color>,
    pub peek_view_result_background: Option<Color>,
    pub peek_view_result_match_highlight_background: Option<Color>,
    pub peek_view_result_foreground: Option<Color>,
    pub peek_view_title_background: Option<Color>,
    pub peek_view_title_label_foreground: Option<Color>,
    pub peek_view_title_description_foreground: Option<Color>,
    pub diff_editor_inserted_text_background: Option<Color>,
    pub diff_editor_removed_text_background: Option<Color>,
    pub diff_editor_inserted_line_background: Option<Color>,
    pub diff_editor_removed_line_background: Option<Color>,
    pub diff_editor_inserted_text_border: Option<Color>,
    pub diff_editor_removed_text_border: Option<Color>,
    pub diff_editor_border: Option<Color>,
    pub diff_editor_diagonal_fill: Option<Color>,
    pub merge_current_header_background: Option<Color>,
    pub merge_current_content_background: Option<Color>,
    pub merge_incoming_header_background: Option<Color>,
    pub merge_incoming_content_background: Option<Color>,
    pub merge_common_header_background: Option<Color>,
    pub merge_common_content_background: Option<Color>,
    pub merge_border: Option<Color>,
    pub minimap_background: Option<Color>,
    pub minimap_selection_highlight: Option<Color>,
    pub minimap_find_match_highlight: Option<Color>,
    pub minimap_error_highlight: Option<Color>,
    pub minimap_warning_highlight: Option<Color>,
    pub minimap_slider_background: Option<Color>,
    pub minimap_slider_hover_background: Option<Color>,
    pub minimap_slider_active_background: Option<Color>,
    pub breadcrumb_foreground: Option<Color>,
    pub breadcrumb_background: Option<Color>,
    pub breadcrumb_focus_foreground: Option<Color>,
    pub breadcrumb_active_selection_foreground: Option<Color>,
    pub breadcrumb_picker_background: Option<Color>,
    pub focus_border: Option<Color>,
    pub foreground: Option<Color>,
    pub disabled_foreground: Option<Color>,
    pub selection_background: Option<Color>,
    pub widget_shadow: Option<Color>,
    pub widget_border: Option<Color>,
    pub description_foreground: Option<Color>,
    pub error_foreground: Option<Color>,
    pub icon_foreground: Option<Color>,
    pub contrast_border: Option<Color>,
    pub contrast_active_border: Option<Color>,
    pub text_link_foreground: Option<Color>,
    pub text_link_active_foreground: Option<Color>,
    pub text_separator_foreground: Option<Color>,
    pub text_preformat_foreground: Option<Color>,
    pub text_preformat_background: Option<Color>,
    pub text_block_quote_background: Option<Color>,
    pub text_block_quote_border: Option<Color>,
    pub text_code_block_background: Option<Color>,
    pub sash_hover_border: Option<Color>,
    pub toolbar_hover_background: Option<Color>,
    pub toolbar_hover_outline: Option<Color>,
    pub toolbar_active_background: Option<Color>,
    pub keybinding_label_background: Option<Color>,
    pub keybinding_label_foreground: Option<Color>,
    pub keybinding_label_border: Option<Color>,
    pub keybinding_label_bottom_border: Option<Color>,
    pub settings_header_foreground: Option<Color>,
    pub settings_modified_item_indicator: Option<Color>,
    pub settings_dropdown_background: Option<Color>,
    pub settings_dropdown_border: Option<Color>,
    pub settings_text_input_border: Option<Color>,
    pub settings_number_input_border: Option<Color>,
    pub checkbox_background: Option<Color>,
    pub checkbox_foreground: Option<Color>,
    pub checkbox_border: Option<Color>,
    pub quick_input_background: Option<Color>,
    pub quick_input_foreground: Option<Color>,
    pub picker_group_border: Option<Color>,
    pub picker_group_foreground: Option<Color>,
    pub debug_toolbar_background: Option<Color>,
    pub welcome_page_tile_background: Option<Color>,
    pub welcome_page_progress_foreground: Option<Color>,
    pub terminal_foreground: Option<Color>,
    pub terminal_background: Option<Color>,
    pub terminal_cursor_foreground: Option<Color>,
    pub terminal_cursor_background: Option<Color>,
    pub terminal_selection_background: Option<Color>,
    pub terminal_inactive_selection_background: Option<Color>,
    pub terminal_tab_active_border: Option<Color>,
    pub testing_icon_passed: Option<Color>,
    pub testing_icon_failed: Option<Color>,
    pub testing_icon_errored: Option<Color>,
    pub testing_icon_skipped: Option<Color>,
    pub testing_icon_queued: Option<Color>,
    pub testing_icon_unset: Option<Color>,
    pub git_decoration_added_resource_foreground: Option<Color>,
    pub git_decoration_modified_resource_foreground: Option<Color>,
    pub git_decoration_deleted_resource_foreground: Option<Color>,
    pub git_decoration_untracked_resource_foreground: Option<Color>,
    pub git_decoration_ignored_resource_foreground: Option<Color>,
    pub git_decoration_conflict_resource_foreground: Option<Color>,
    pub git_decoration_submodule_resource_foreground: Option<Color>,
}

impl WorkbenchColors {
    /// Default dark workbench colors (based on VS Code "Dark Modern").
    #[allow(clippy::too_many_lines)]
    pub fn default_dark() -> Self {
        Self {
            editor_background: c("#1F1F1F"),
            editor_foreground: c("#CCCCCC"),
            editor_line_highlight_background: c("#2a2d2e"),
            editor_selection_background: c("#264f78"),
            editor_selection_highlight_background: c("#264f7840"),
            editor_find_match_background: c("#9E6A03"),
            editor_find_match_highlight_background: c("#EA5C0055"),
            editor_find_range_highlight_background: c("#3a3d4166"),
            editor_word_highlight_background: c("#575757b8"),
            editor_word_highlight_strong_background: c("#004972b8"),
            editor_line_number_foreground: c("#6E7681"),
            editor_line_number_active_foreground: c("#CCCCCC"),
            editor_cursor_foreground: c("#aeafad"),
            editor_whitespace_foreground: c("#3b3b3b"),
            editor_indent_guide_background: c("#404040"),
            editor_indent_guide_active_background: c("#707070"),
            editor_bracket_match_background: c("#0064001a"),
            editor_bracket_match_border: c("#888888"),
            editor_overview_ruler_border: c("#010409"),
            editor_gutter_added_background: c("#2EA043"),
            editor_gutter_modified_background: c("#0078D4"),
            editor_gutter_deleted_background: c("#F85149"),
            editor_error_foreground: c("#F14C4C"),
            editor_warning_foreground: c("#CCA700"),
            editor_info_foreground: c("#3794ff"),
            editor_hover_highlight_background: c("#264f7840"),
            editor_link_active_foreground: c("#4E94CE"),
            editor_sticky_scroll_background: c("#1F1F1F"),
            editor_widget_background: c("#202020"),
            editor_widget_foreground: c("#CCCCCC"),
            editor_suggest_widget_background: c("#252526"),
            editor_hover_widget_background: c("#252526"),
            editor_inlay_hint_foreground: c("#969696"),
            editor_light_bulb_foreground: c("#FFCC00"),
            editor_light_bulb_auto_fix_foreground: c("#75BEFF"),
            editor_group_border: c("#FFFFFF17"),
            editor_group_header_tabs_background: c("#181818"),
            editor_group_header_tabs_border: c("#2B2B2B"),
            side_bar_background: c("#181818"),
            side_bar_foreground: c("#CCCCCC"),
            side_bar_border: c("#2B2B2B"),
            side_bar_title_foreground: c("#CCCCCC"),
            side_bar_section_header_background: c("#181818"),
            side_bar_section_header_foreground: c("#CCCCCC"),
            side_bar_section_header_border: c("#2B2B2B"),
            activity_bar_background: c("#181818"),
            activity_bar_foreground: c("#D7D7D7"),
            activity_bar_inactive_foreground: c("#868686"),
            activity_bar_border: c("#2B2B2B"),
            activity_bar_active_border: c("#0078D4"),
            activity_bar_badge_background: c("#0078D4"),
            activity_bar_badge_foreground: c("#FFFFFF"),
            status_bar_background: c("#181818"),
            status_bar_foreground: c("#CCCCCC"),
            status_bar_border: c("#2B2B2B"),
            status_bar_debugging_background: c("#0078D4"),
            status_bar_debugging_foreground: c("#FFFFFF"),
            status_bar_no_folder_background: c("#1F1F1F"),
            status_bar_item_hover_background: c("#F1F1F133"),
            status_bar_item_prominent_background: c("#6E768166"),
            status_bar_item_remote_background: c("#0078D4"),
            status_bar_item_remote_foreground: c("#FFFFFF"),
            tab_active_background: c("#1F1F1F"),
            tab_active_foreground: c("#FFFFFF"),
            tab_inactive_background: c("#181818"),
            tab_inactive_foreground: c("#9D9D9D"),
            tab_border: c("#2B2B2B"),
            tab_active_border_top: c("#0078D4"),
            tab_hover_background: c("#1F1F1F"),
            panel_background: c("#181818"),
            panel_border: c("#2B2B2B"),
            panel_title_active_foreground: c("#CCCCCC"),
            panel_title_active_border: c("#0078D4"),
            panel_title_inactive_foreground: c("#9D9D9D"),
            panel_input_border: c("#2B2B2B"),
            list_hover_background: c("#2a2d2e"),
            list_active_selection_background: c("#04395e"),
            list_active_selection_foreground: c("#ffffff"),
            list_inactive_selection_background: c("#37373d"),
            list_focus_background: c("#04395e"),
            list_highlight_foreground: c("#2AAAFF"),
            list_drop_background: c("#062F4A"),
            list_error_foreground: c("#F88070"),
            list_warning_foreground: c("#CCA700"),
            tree_indent_guides_stroke: c("#585858"),
            input_background: c("#313131"),
            input_foreground: c("#CCCCCC"),
            input_border: c("#3C3C3C"),
            input_placeholder_foreground: c("#989898"),
            input_option_active_background: c("#2489DB82"),
            input_option_active_border: c("#2488DB"),
            input_validation_warning_background: c("#352A05"),
            input_validation_warning_border: c("#B89500"),
            input_validation_error_background: c("#5A1D1D"),
            input_validation_error_border: c("#BE1100"),
            input_validation_info_background: c("#063B49"),
            input_validation_info_border: c("#007acc"),
            dropdown_background: c("#313131"),
            dropdown_foreground: c("#CCCCCC"),
            dropdown_border: c("#3C3C3C"),
            dropdown_list_background: c("#1F1F1F"),
            button_background: c("#0078D4"),
            button_foreground: c("#FFFFFF"),
            button_hover_background: c("#026EC1"),
            button_border: c("#ffffff1a"),
            button_secondary_background: c("#00000000"),
            button_secondary_foreground: c("#CCCCCC"),
            button_secondary_hover_background: c("#2B2B2B"),
            badge_background: c("#616161"),
            badge_foreground: c("#F8F8F8"),
            scroll_bar_shadow: c("#000000"),
            scrollbar_slider_background: c("#79797966"),
            scrollbar_slider_hover_background: c("#646464b3"),
            scrollbar_slider_active_background: c("#bfbfbf66"),
            progress_bar_background: c("#0078D4"),
            notification_background: c("#1F1F1F"),
            notification_foreground: c("#CCCCCC"),
            notification_border: c("#2B2B2B"),
            notification_center_header_background: c("#1F1F1F"),
            notification_center_header_foreground: c("#CCCCCC"),
            title_bar_active_background: c("#181818"),
            title_bar_active_foreground: c("#CCCCCC"),
            title_bar_inactive_background: c("#1F1F1F"),
            title_bar_inactive_foreground: c("#9D9D9D"),
            title_bar_border: c("#2B2B2B"),
            menu_background: c("#1F1F1F"),
            menu_selection_background: c("#0078d4"),
            peek_view_border: c("#007acc"),
            peek_view_editor_background: c("#1F1F1F"),
            peek_view_editor_match_highlight_background: c("#BB800966"),
            peek_view_result_background: c("#1F1F1F"),
            peek_view_result_match_highlight_background: c("#BB800966"),
            peek_view_title_background: c("#1e1e1e"),
            diff_editor_inserted_text_background: c("#9ccc2c33"),
            diff_editor_removed_text_background: c("#ff000033"),
            merge_current_header_background: c("#40c8ae80"),
            merge_incoming_header_background: c("#40a6ff80"),
            minimap_selection_highlight: c("#264f7899"),
            minimap_find_match_highlight: c("#d18616"),
            breadcrumb_foreground: c("#cccccccc"),
            breadcrumb_focus_foreground: c("#e0e0e0"),
            breadcrumb_active_selection_foreground: c("#e0e0e0"),
            focus_border: c("#0078D4"),
            foreground: c("#CCCCCC"),
            disabled_foreground: c("#CCCCCC80"),
            selection_background: c("#264f78"),
            widget_shadow: c("#0000005c"),
            widget_border: c("#313131"),
            description_foreground: c("#9D9D9D"),
            error_foreground: c("#F85149"),
            icon_foreground: c("#CCCCCC"),
            text_link_foreground: c("#4daafc"),
            text_link_active_foreground: c("#4daafc"),
            text_preformat_foreground: c("#D0D0D0"),
            text_preformat_background: c("#3C3C3C"),
            text_block_quote_background: c("#2B2B2B"),
            text_block_quote_border: c("#616161"),
            text_code_block_background: c("#2B2B2B"),
            toolbar_hover_background: c("#5a5d5e50"),
            keybinding_label_foreground: c("#CCCCCC"),
            settings_header_foreground: c("#FFFFFF"),
            settings_modified_item_indicator: c("#BB800966"),
            settings_dropdown_background: c("#313131"),
            settings_dropdown_border: c("#3C3C3C"),
            checkbox_background: c("#313131"),
            checkbox_border: c("#3C3C3C"),
            quick_input_background: c("#222222"),
            quick_input_foreground: c("#CCCCCC"),
            picker_group_border: c("#3C3C3C"),
            debug_toolbar_background: c("#181818"),
            welcome_page_tile_background: c("#2B2B2B"),
            welcome_page_progress_foreground: c("#0078D4"),
            terminal_foreground: c("#CCCCCC"),
            terminal_tab_active_border: c("#0078D4"),
            ..Self::default()
        }
    }

    /// Default light workbench colors (based on VS Code "Light Modern").
    #[allow(clippy::too_many_lines)]
    pub fn default_light() -> Self {
        Self {
            editor_background: c("#FFFFFF"),
            editor_foreground: c("#3B3B3B"),
            editor_line_highlight_background: c("#f0f0f0"),
            editor_selection_background: c("#add6ff"),
            editor_selection_highlight_background: c("#ADD6FF80"),
            editor_find_match_background: c("#a8ac94"),
            editor_find_match_highlight_background: c("#EA5C0055"),
            editor_find_range_highlight_background: c("#b4b4b44d"),
            editor_line_number_foreground: c("#6E7681"),
            editor_line_number_active_foreground: c("#171184"),
            editor_cursor_foreground: c("#000000"),
            editor_whitespace_foreground: c("#d3d3d3"),
            editor_indent_guide_background: c("#d3d3d3"),
            editor_indent_guide_active_background: c("#939393"),
            editor_bracket_match_background: c("#0064001a"),
            editor_bracket_match_border: c("#b9b9b9"),
            editor_overview_ruler_border: c("#E5E5E5"),
            editor_gutter_added_background: c("#2EA043"),
            editor_gutter_modified_background: c("#005FB8"),
            editor_gutter_deleted_background: c("#F85149"),
            editor_error_foreground: c("#e51400"),
            editor_warning_foreground: c("#bf8803"),
            editor_info_foreground: c("#1a85ff"),
            editor_link_active_foreground: c("#0000ff"),
            editor_sticky_scroll_background: c("#FFFFFF"),
            editor_widget_background: c("#F8F8F8"),
            editor_widget_foreground: c("#3B3B3B"),
            editor_suggest_widget_background: c("#F8F8F8"),
            editor_inlay_hint_foreground: c("#969696"),
            editor_light_bulb_foreground: c("#DDB100"),
            editor_light_bulb_auto_fix_foreground: c("#007ACC"),
            editor_group_border: c("#E5E5E5"),
            editor_group_header_tabs_background: c("#F8F8F8"),
            editor_group_header_tabs_border: c("#E5E5E5"),
            side_bar_background: c("#F8F8F8"),
            side_bar_foreground: c("#3B3B3B"),
            side_bar_border: c("#E5E5E5"),
            side_bar_title_foreground: c("#3B3B3B"),
            side_bar_section_header_background: c("#F8F8F8"),
            side_bar_section_header_foreground: c("#3B3B3B"),
            side_bar_section_header_border: c("#E5E5E5"),
            activity_bar_background: c("#F8F8F8"),
            activity_bar_foreground: c("#1F1F1F"),
            activity_bar_inactive_foreground: c("#616161"),
            activity_bar_border: c("#E5E5E5"),
            activity_bar_active_border: c("#005FB8"),
            activity_bar_badge_background: c("#005FB8"),
            activity_bar_badge_foreground: c("#FFFFFF"),
            status_bar_background: c("#F8F8F8"),
            status_bar_foreground: c("#3B3B3B"),
            status_bar_border: c("#E5E5E5"),
            status_bar_debugging_background: c("#FD716C"),
            status_bar_debugging_foreground: c("#000000"),
            status_bar_no_folder_background: c("#F8F8F8"),
            status_bar_item_hover_background: c("#1F1F1F11"),
            status_bar_item_prominent_background: c("#6E768166"),
            status_bar_item_remote_background: c("#005FB8"),
            status_bar_item_remote_foreground: c("#FFFFFF"),
            tab_active_background: c("#FFFFFF"),
            tab_active_foreground: c("#3B3B3B"),
            tab_inactive_background: c("#F8F8F8"),
            tab_inactive_foreground: c("#868686"),
            tab_border: c("#E5E5E5"),
            tab_active_border_top: c("#005FB8"),
            tab_hover_background: c("#FFFFFF"),
            tab_last_pinned_border: c("#D4D4D4"),
            panel_background: c("#F8F8F8"),
            panel_border: c("#E5E5E5"),
            panel_title_active_foreground: c("#3B3B3B"),
            panel_title_active_border: c("#005FB8"),
            panel_title_inactive_foreground: c("#3B3B3B"),
            panel_input_border: c("#E5E5E5"),
            list_hover_background: c("#F2F2F2"),
            list_active_selection_background: c("#E8E8E8"),
            list_active_selection_foreground: c("#000000"),
            list_active_selection_icon_foreground: c("#000000"),
            list_inactive_selection_background: c("#E4E6F1"),
            list_focus_background: c("#d6ebff"),
            list_highlight_foreground: c("#0066bf"),
            list_drop_background: c("#D6EBFF"),
            list_error_foreground: c("#B01011"),
            list_warning_foreground: c("#855F00"),
            tree_indent_guides_stroke: c("#a9a9a9"),
            input_background: c("#FFFFFF"),
            input_foreground: c("#3B3B3B"),
            input_border: c("#CECECE"),
            input_placeholder_foreground: c("#767676"),
            input_option_active_background: c("#BED6ED"),
            input_option_active_border: c("#005FB8"),
            input_option_active_foreground: c("#000000"),
            input_validation_warning_background: c("#F6F5D2"),
            input_validation_warning_border: c("#B89500"),
            input_validation_error_background: c("#F2DEDE"),
            input_validation_error_border: c("#BE1100"),
            input_validation_info_background: c("#D6ECF2"),
            input_validation_info_border: c("#007acc"),
            dropdown_background: c("#FFFFFF"),
            dropdown_foreground: c("#3B3B3B"),
            dropdown_border: c("#CECECE"),
            dropdown_list_background: c("#FFFFFF"),
            button_background: c("#005FB8"),
            button_foreground: c("#FFFFFF"),
            button_hover_background: c("#0258A8"),
            button_border: c("#0000001a"),
            button_secondary_background: c("#E5E5E5"),
            button_secondary_foreground: c("#3B3B3B"),
            button_secondary_hover_background: c("#CCCCCC"),
            badge_background: c("#CCCCCC"),
            badge_foreground: c("#3B3B3B"),
            scroll_bar_shadow: c("#DDDDDD"),
            scrollbar_slider_background: c("#64646466"),
            scrollbar_slider_hover_background: c("#646464b3"),
            scrollbar_slider_active_background: c("#00000099"),
            progress_bar_background: c("#005FB8"),
            notification_background: c("#FFFFFF"),
            notification_foreground: c("#3B3B3B"),
            notification_border: c("#E5E5E5"),
            notification_center_header_background: c("#FFFFFF"),
            notification_center_header_foreground: c("#3B3B3B"),
            title_bar_active_background: c("#F8F8F8"),
            title_bar_active_foreground: c("#1E1E1E"),
            title_bar_inactive_background: c("#F8F8F8"),
            title_bar_inactive_foreground: c("#8B949E"),
            title_bar_border: c("#E5E5E5"),
            menu_border: c("#CECECE"),
            menu_selection_background: c("#005FB8"),
            menu_selection_foreground: c("#ffffff"),
            peek_view_border: c("#007acc"),
            peek_view_result_background: c("#FFFFFF"),
            peek_view_result_match_highlight_background: c("#BB800966"),
            peek_view_editor_match_highlight_background: c("#BB800966"),
            diff_editor_inserted_text_background: c("#9ccc2c40"),
            diff_editor_removed_text_background: c("#ff000033"),
            merge_current_header_background: c("#40c8ae80"),
            merge_incoming_header_background: c("#40a6ff80"),
            minimap_selection_highlight: c("#add6ff"),
            minimap_find_match_highlight: c("#d18616"),
            breadcrumb_foreground: c("#616161cc"),
            breadcrumb_focus_foreground: c("#2f2f2f"),
            breadcrumb_active_selection_foreground: c("#2f2f2f"),
            focus_border: c("#005FB8"),
            foreground: c("#3B3B3B"),
            disabled_foreground: c("#61616180"),
            selection_background: c("#add6ff"),
            widget_shadow: c("#00000029"),
            widget_border: c("#E5E5E5"),
            description_foreground: c("#3B3B3B"),
            error_foreground: c("#F85149"),
            icon_foreground: c("#3B3B3B"),
            text_link_foreground: c("#005FB8"),
            text_link_active_foreground: c("#005FB8"),
            text_preformat_foreground: c("#3B3B3B"),
            text_preformat_background: c("#0000001F"),
            text_block_quote_background: c("#F8F8F8"),
            text_block_quote_border: c("#E5E5E5"),
            text_code_block_background: c("#F8F8F8"),
            toolbar_hover_background: c("#b8b8b850"),
            keybinding_label_foreground: c("#3B3B3B"),
            settings_header_foreground: c("#1F1F1F"),
            settings_modified_item_indicator: c("#BB800966"),
            settings_dropdown_background: c("#FFFFFF"),
            settings_dropdown_border: c("#CECECE"),
            settings_text_input_border: c("#CECECE"),
            settings_number_input_border: c("#CECECE"),
            checkbox_background: c("#F8F8F8"),
            checkbox_border: c("#CECECE"),
            quick_input_background: c("#F8F8F8"),
            quick_input_foreground: c("#3B3B3B"),
            picker_group_border: c("#E5E5E5"),
            picker_group_foreground: c("#8B949E"),
            welcome_page_tile_background: c("#F3F3F3"),
            terminal_foreground: c("#3B3B3B"),
            terminal_cursor_foreground: c("#005FB8"),
            terminal_inactive_selection_background: c("#E5EBF1"),
            terminal_tab_active_border: c("#005FB8"),
            ..Self::default()
        }
    }
}

fn c(hex: &str) -> Option<Color> {
    Color::from_hex(hex).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_dark_has_editor_bg() {
        let dark = WorkbenchColors::default_dark();
        assert!(dark.editor_background.is_some());
    }

    #[test]
    fn default_light_has_editor_bg() {
        let light = WorkbenchColors::default_light();
        assert!(light.editor_background.is_some());
    }

    #[test]
    fn default_is_all_none() {
        let d = WorkbenchColors::default();
        assert!(d.editor_background.is_none());
        assert!(d.side_bar_background.is_none());
    }

    #[test]
    fn serde_roundtrip() {
        let colors = WorkbenchColors::default_dark();
        let json = serde_json::to_string(&colors).unwrap();
        let parsed: WorkbenchColors = serde_json::from_str(&json).unwrap();
        assert_eq!(colors, parsed);
    }
}
